spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:43306/books?serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

jwt:
  secret: "c0e45555-76ca-410a-9b5e-de18ebccc036"
  expiration: 999999
